/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import inject.Inject;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author UPHM
 */
public class DlgTransactionConfirm extends javax.swing.JDialog {

    /**
     * Creates new form DlgTransactionConfirm
     */
    private Connection myConn = null;
    private PreparedStatement myStmt = null;

    private final DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    private Date date;
    private final String template = "Rp %,.02f";

    private double photocopyPrice;
    private double scanPrice;
    private double printPrice;
    private double totalFee;
    private Student student;
    
    private Inject inject;
    
    public DlgTransactionConfirm(java.awt.Frame parent, boolean modal, Connection conn,Inject inject) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        myConn=conn;
        this.inject=inject;
    }

    public void generateData(Student student, int photocopy, int scan, int print) {
        date = new Date();
        this.student = student;
        txtTransactionDate.setText(dateFormat.format(date));
        txtTransactionID.setText(student.getNim());
        txtTransactionName.setText(student.getName());
        txtTransactionClass.setText(student.getKelas());
        txtTransactionStudyProgram.setText(student.getStudiProgram());

        photocopyPrice = photocopy * 200;
        scanPrice = scan * 2500;
        printPrice = print * 1000;
        totalFee = photocopyPrice + scanPrice + printPrice;
        txtTransactionPhotocopy.setText(String.format(template, photocopyPrice));
        txtTransactionScanning.setText(String.format(template, scanPrice));
        txtTransactionPrinting.setText(String.format(template, printPrice));
        txtTransactionTotalFee.setText(String.format(template, totalFee));
    }

    private void registerTransaction() {

        try {
            // Prepare statement
            myStmt = myConn
                    .prepareStatement("INSERT INTO `library`.`transaction` (`date`, `Student_ID`, `photocopy`, `scanning`, `printing`, `fee`) "
                            + "VALUES (?,?,?,?,?,?);");

            myStmt.setString(1, dateFormat.format(date));
            myStmt.setString(2, student.getNim());
            myStmt.setDouble(3, photocopyPrice);
            myStmt.setDouble(4, scanPrice);
            myStmt.setDouble(5, printPrice);
            myStmt.setDouble(6, totalFee);

            // Execute SQL query
            myStmt.executeUpdate();

            myStmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtTransactionTotalFee = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTransactionPrinting = new javax.swing.JLabel();
        txtTransactionScanning = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTransactionPhotocopy = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTransactionStudyProgram = new javax.swing.JLabel();
        txtTransactionClass = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTransactionName = new javax.swing.JLabel();
        txtTransactionID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTransactionDate = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.confirm.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.CONFIRMhover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 550, 185, 100);

        txtTransactionTotalFee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTransactionTotalFee.setText("jLabel11");
        jPanel1.add(txtTransactionTotalFee);
        txtTransactionTotalFee.setBounds(310, 490, 200, 14);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Total Fee:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 490, 80, 14);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Printing:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(223, 460, 60, 20);

        txtTransactionPrinting.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTransactionPrinting.setText("jLabel13");
        jPanel1.add(txtTransactionPrinting);
        txtTransactionPrinting.setBounds(310, 460, 190, 14);

        txtTransactionScanning.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTransactionScanning.setText("jLabel12");
        jPanel1.add(txtTransactionScanning);
        txtTransactionScanning.setBounds(310, 430, 190, 14);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Scanning:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(215, 430, 90, 20);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Photocopy:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 400, 90, 14);

        txtTransactionPhotocopy.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTransactionPhotocopy.setText("jLabel11");
        jPanel1.add(txtTransactionPhotocopy);
        txtTransactionPhotocopy.setBounds(310, 400, 190, 14);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel10.setText("Service");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(260, 330, 100, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setText("Study Program:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(170, 270, 120, 20);

        txtTransactionStudyProgram.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTransactionStudyProgram.setText("jLabel8");
        jPanel1.add(txtTransactionStudyProgram);
        txtTransactionStudyProgram.setBounds(310, 270, 180, 14);

        txtTransactionClass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTransactionClass.setText("jLabel7");
        jPanel1.add(txtTransactionClass);
        txtTransactionClass.setBounds(310, 240, 180, 14);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Class:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 240, 50, 14);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Name:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 210, 49, 14);

        txtTransactionName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTransactionName.setText("jLabel6");
        jPanel1.add(txtTransactionName);
        txtTransactionName.setBounds(310, 210, 180, 14);

        txtTransactionID.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTransactionID.setText("jLabel5");
        jPanel1.add(txtTransactionID);
        txtTransactionID.setBounds(310, 180, 180, 14);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("ID:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 180, 30, 14);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Date:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 150, 50, 14);

        txtTransactionDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtTransactionDate.setText("jLabel6");
        jPanel1.add(txtTransactionDate);
        txtTransactionDate.setBounds(310, 150, 180, 14);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.back.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.BACKhover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(90, 560, 180, 80);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dlg.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 630, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registerTransaction();
        dispose();
        inject.getFrmMain().changeLayout(inject.getPnlLogin());
        inject.getPnlUser().clearData();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtTransactionClass;
    private javax.swing.JLabel txtTransactionDate;
    private javax.swing.JLabel txtTransactionID;
    private javax.swing.JLabel txtTransactionName;
    private javax.swing.JLabel txtTransactionPhotocopy;
    private javax.swing.JLabel txtTransactionPrinting;
    private javax.swing.JLabel txtTransactionScanning;
    private javax.swing.JLabel txtTransactionStudyProgram;
    private javax.swing.JLabel txtTransactionTotalFee;
    // End of variables declaration//GEN-END:variables
}
