/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import inject.Inject;
import java.sql.Connection;
import javax.swing.JCheckBox;
import org.jdesktop.xswingx.JXFormattedTextField;
import util.SUtility;

/**
 *
 * @author UPHM
 */
public class PnlUser extends javax.swing.JPanel {

    /**
     * Creates new form PnlUer
     */
    private Connection myConn = null;

    private Inject inject;
    private Student student;

    public PnlUser(Connection conn, Inject inject) {
        initComponents();
        myConn = conn;
        this.inject = inject;
    }

    private void backToLogin() {
        inject.getFrmMain().changeLayout(inject.getPnlLogin());
        clearData();
    }

    public void generateData(Student student) {
        this.student = student;
        txtUserID.setText(student.getNim());
        txtUserName.setText(student.getName());
        txtUserClass.setText(student.getKelas());
        txtUserStudyProgram.setText(student.getStudiProgram());
    }

    public void clearData() {
        chkUserPhotoCopy.setSelected(false);
        txtUserPhotoCopyQty.setEditable(false);
        txtUserPhotoCopyQty.setText("");
        chkUserScanning.setSelected(false);
        txtUserScanQty.setEditable(false);
        txtUserScanQty.setText("");
        chkUserPrinting.setSelected(false);
        txtUserPrintQty.setEditable(false);
        txtUserPrintQty.setText("");
    }

    private void checkboxValidate(JCheckBox chk, JXFormattedTextField txt) {
        if (chk.isSelected()) {
            txt.setText("");
            txt.setEditable(true);
            txt.requestFocusInWindow();
        } else {
            txt.setText("");
            txt.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        txtUserClass = new javax.swing.JLabel();
        txtUserStudyProgram = new javax.swing.JLabel();
        chkUserPhotoCopy = new javax.swing.JCheckBox();
        chkUserScanning = new javax.swing.JCheckBox();
        chkUserPrinting = new javax.swing.JCheckBox();
        txtUserPhotoCopyQty = new org.jdesktop.xswingx.JXFormattedTextField();
        txtUserScanQty = new org.jdesktop.xswingx.JXFormattedTextField();
        txtUserPrintQty = new org.jdesktop.xswingx.JXFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.back.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.BACKhover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(630, 690, 160, 60);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Name:");
        add(jLabel1);
        jLabel1.setBounds(702, 170, 50, 23);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Class:");
        add(jLabel2);
        jLabel2.setBounds(708, 200, 50, 23);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Study Program:");
        add(jLabel3);
        jLabel3.setBounds(639, 230, 120, 23);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("ID:");
        add(jLabel4);
        jLabel4.setBounds(730, 140, 30, 23);

        txtUserID.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtUserID.setText("jLabel5");
        add(txtUserID);
        txtUserID.setBounds(790, 140, 220, 23);

        txtUserName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtUserName.setText("jLabel6");
        add(txtUserName);
        txtUserName.setBounds(790, 170, 220, 23);

        txtUserClass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtUserClass.setText("jLabel7");
        add(txtUserClass);
        txtUserClass.setBounds(790, 200, 220, 23);

        txtUserStudyProgram.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtUserStudyProgram.setText("jLabel8");
        add(txtUserStudyProgram);
        txtUserStudyProgram.setBounds(790, 230, 220, 23);

        chkUserPhotoCopy.setBackground(new java.awt.Color(231, 246, 251));
        chkUserPhotoCopy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkUserPhotoCopy.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chkUserPhotoCopy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkUserPhotoCopy.setMaximumSize(new java.awt.Dimension(50, 50));
        chkUserPhotoCopy.setMinimumSize(new java.awt.Dimension(50, 50));
        chkUserPhotoCopy.setPreferredSize(new java.awt.Dimension(50, 50));
        chkUserPhotoCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUserPhotoCopyActionPerformed(evt);
            }
        });
        add(chkUserPhotoCopy);
        chkUserPhotoCopy.setBounds(510, 480, 30, 30);

        chkUserScanning.setBackground(new java.awt.Color(231, 246, 251));
        chkUserScanning.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chkUserScanning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkUserScanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUserScanningActionPerformed(evt);
            }
        });
        add(chkUserScanning);
        chkUserScanning.setBounds(510, 538, 30, 30);

        chkUserPrinting.setBackground(new java.awt.Color(231, 246, 251));
        chkUserPrinting.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        chkUserPrinting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkUserPrinting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUserPrintingActionPerformed(evt);
            }
        });
        add(chkUserPrinting);
        chkUserPrinting.setBounds(510, 595, 30, 30);

        txtUserPhotoCopyQty.setEditable(false);
        txtUserPhotoCopyQty.setBackground(new java.awt.Color(255, 255, 255));
        txtUserPhotoCopyQty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUserPhotoCopyQty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUserPhotoCopyQty.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        txtUserPhotoCopyQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtUserPhotoCopyQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserPhotoCopyQtyActionPerformed(evt);
            }
        });
        add(txtUserPhotoCopyQty);
        txtUserPhotoCopyQty.setBounds(670, 470, 400, 40);

        txtUserScanQty.setEditable(false);
        txtUserScanQty.setBackground(new java.awt.Color(255, 255, 255));
        txtUserScanQty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUserScanQty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUserScanQty.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        txtUserScanQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        add(txtUserScanQty);
        txtUserScanQty.setBounds(670, 530, 400, 40);

        txtUserPrintQty.setEditable(false);
        txtUserPrintQty.setBackground(new java.awt.Color(255, 255, 255));
        txtUserPrintQty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUserPrintQty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUserPrintQty.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        txtUserPrintQty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtUserPrintQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserPrintQtyActionPerformed(evt);
            }
        });
        add(txtUserPrintQty);
        txtUserPrintQty.setBounds(670, 590, 400, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.confirm.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.CONFIRMhover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(820, 690, 160, 60);

        jLabel6.setBackground(new java.awt.Color(231, 246, 251));
        jLabel6.setOpaque(true);
        add(jLabel6);
        jLabel6.setBounds(500, 470, 40, 160);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 1600, 900);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        backToLogin();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkUserPhotoCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUserPhotoCopyActionPerformed
        checkboxValidate(chkUserPhotoCopy, txtUserPhotoCopyQty);
    }//GEN-LAST:event_chkUserPhotoCopyActionPerformed

    private void txtUserPhotoCopyQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserPhotoCopyQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPhotoCopyQtyActionPerformed

    private void chkUserScanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUserScanningActionPerformed
        checkboxValidate(chkUserScanning, txtUserScanQty);
    }//GEN-LAST:event_chkUserScanningActionPerformed

    private void chkUserPrintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUserPrintingActionPerformed
        checkboxValidate(chkUserPrinting, txtUserPrintQty);
    }//GEN-LAST:event_chkUserPrintingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int photocopy;
        int scan;
        int print;
        if ((!txtUserPhotoCopyQty.getText().trim().isEmpty() && Integer.valueOf(txtUserPhotoCopyQty.getText()) > 0)
                || (!txtUserPrintQty.getText().trim().isEmpty() && Integer.valueOf(txtUserPrintQty.getText()) > 0)
                || (!txtUserScanQty.getText().trim().isEmpty() && Integer.valueOf(txtUserScanQty.getText()) > 0)) {

            if (txtUserPhotoCopyQty.getText().trim().isEmpty()) {
                photocopy = 0;
            } else {
                photocopy = Integer.valueOf(txtUserPhotoCopyQty.getText());
            }
            if (txtUserScanQty.getText().trim().isEmpty()) {
                scan = 0;
            } else {
                scan = Integer.valueOf(txtUserScanQty.getText());
            }
            if (txtUserPrintQty.getText().trim().isEmpty()) {
                print = 0;
            } else {
                print = Integer.valueOf(txtUserPrintQty.getText());
            }

            DlgTransactionConfirm dlg = new DlgTransactionConfirm(inject.getFrmMain(), true, myConn, inject);
            dlg.generateData(student, photocopy, scan, print);
            dlg.setVisible(true);

        } else {
            SUtility.msg(this, "No transaction!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtUserPrintQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserPrintQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPrintQtyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkUserPhotoCopy;
    private javax.swing.JCheckBox chkUserPrinting;
    private javax.swing.JCheckBox chkUserScanning;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel txtUserClass;
    private javax.swing.JLabel txtUserID;
    private javax.swing.JLabel txtUserName;
    private org.jdesktop.xswingx.JXFormattedTextField txtUserPhotoCopyQty;
    private org.jdesktop.xswingx.JXFormattedTextField txtUserPrintQty;
    private org.jdesktop.xswingx.JXFormattedTextField txtUserScanQty;
    private javax.swing.JLabel txtUserStudyProgram;
    // End of variables declaration//GEN-END:variables
}
